### ISSUE TITLE
Inconsistent licensing: Unlicense vs MIT

### ISSUE THREAD

**Issue by ngwese** [PSeitz/cool-id-generator#3]
The [Cargo.toml](https://github.com/PSeitz/cool-id-generator/blob/main/Cargo.toml#L11) file for this project lists the crate license as `Unlicense` while the repository itself contains an [MIT](https://github.com/PSeitz/cool-id-generator/blob/main/LICENSE) license file.

The inconsistent licensing makes it difficult to ensure proper attribution when this crate (and others which pull it in such as `chitchat`) are used.

**Comment by PSeitz** [comment]
Thanks, I fixed it by changing the License to MIT.
